version: '3'

services:
    mysql:
        image: mysql:5.7
        container_name: container-mysql
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'password'

    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin
        container_name: container-phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=password
        restart: always
        ports:
            - "8080:80"
        links: 
            - mysql

    php-apache:
        depends_on:
            - mysql
        container_name: container-php-apache
        build: ./php
        volumes:
            - ./htdocs:/var/www/html
        restart: always
        ports: 
            - "80:80"
        links:
            - mysql

volumes:
    db_data: {} 